-- Mon Oct 23 15:49:44 UTC 2017: file automatically generated by load_data_lake.sh
DROP TABLE ComplicationsHospital;
CREATE EXTERNAL TABLE ComplicationsHospital
(
	ProviderID STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	PhoneNumber STRING,
	MeasureName STRING,
	MeasureID STRING,
	ComparedtoNational STRING,
	Denominator STRING,
	Score STRING,
	LowerEstimate STRING,
	HigherEstimate STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/ComplicationsHospital";



DROP TABLE ComplicationsNational;
CREATE EXTERNAL TABLE ComplicationsNational
(
	MeasureName STRING,
	MeasureID STRING,
	NationalRate STRING,
	NumberofHospitalsWorse STRING,
	NumberofHospitalsSame STRING,
	NumberofHospitalsBetter STRING,
	NumberofHospitalsTooFew STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/ComplicationsNational";



DROP TABLE ComplicationsState;
CREATE EXTERNAL TABLE ComplicationsState
(
	State STRING,
	MeasureName STRING,
	MeasureID STRING,
	NumberofHospitalsWorse STRING,
	NumberofHospitalsSame STRING,
	NumberofHospitalsBetter STRING,
	NumberofHospitalsTooFew STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/ComplicationsState";



DROP TABLE FootnoteCrosswalk;
CREATE EXTERNAL TABLE FootnoteCrosswalk
(
	Footnote STRING,
	FootnoteText STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/FootnoteCrosswalk";



DROP TABLE FY2013_Distribution_of_Net_Change_in_Base_Op_DRG_Payment_Amt;
CREATE EXTERNAL TABLE FY2013_Distribution_of_Net_Change_in_Base_Op_DRG_Payment_Amt
(
	Percentile STRING,
	NetChangeinBaseOperatingDRGPaymentAmount STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/FY2013_Distribution_of_Net_Change_in_Base_Op_DRG_Payment_Amt";



DROP TABLE FY2013_Net_Change_in_Base_Op_DRG_Payment_Amt;
CREATE EXTERNAL TABLE FY2013_Net_Change_in_Base_Op_DRG_Payment_Amt
(
	NetChangeinBaseOperatingDRGPaymentAmount STRING,
	NumberofHospitalsReceivingthisRange STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/FY2013_Net_Change_in_Base_Op_DRG_Payment_Amt";



DROP TABLE FY2013_Percent_Change_in_Medicare_Payments;
CREATE EXTERNAL TABLE FY2013_Percent_Change_in_Medicare_Payments
(
	ChangeinBaseOperatingDRGPaymentAmount STRING,
	NumberofHospitalsReceivingthisChange STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/FY2013_Percent_Change_in_Medicare_Payments";



DROP TABLE FY2013_Value_Based_Incentive_Payment_Amount;
CREATE EXTERNAL TABLE FY2013_Value_Based_Incentive_Payment_Amount
(
	IncentivePaymentRange STRING,
	NumberofHospitalsReceivingthisRange STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/FY2013_Value_Based_Incentive_Payment_Amount";



DROP TABLE HCAHPSHospital;
CREATE EXTERNAL TABLE HCAHPSHospital
(
	ProviderID STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	PhoneNumber STRING,
	HCAHPSMeasureID STRING,
	HCAHPSQuestion STRING,
	HCAHPSAnswerDescription STRING,
	PatientSurveyStarRating STRING,
	PatientSurveyStarRatingFootnote STRING,
	HCAHPSAnswerPercent STRING,
	HCAHPSAnswerPercentFootnote STRING,
	NumberofCompletedSurveys STRING,
	NumberofCompletedSurveysFootnote STRING,
	SurveyResponseRatePercent STRING,
	SurveyResponseRatePercentFootnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HCAHPSHospital";



DROP TABLE HCAHPSNational;
CREATE EXTERNAL TABLE HCAHPSNational
(
	HCAHPSMeasureID STRING,
	HCAHPSQuestion STRING,
	HCAHPSAnswerDescription STRING,
	HCAHPSAnswerPercent STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HCAHPSNational";



DROP TABLE HCAHPSState;
CREATE EXTERNAL TABLE HCAHPSState
(
	State STRING,
	HCAHPSQuestion STRING,
	HCAHPSMeasureID STRING,
	HCAHPSAnswerDescription STRING,
	HCAHPSAnswerPercent STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HCAHPSState";



DROP TABLE HealthcareAssociatedInfectionsHospital;
CREATE EXTERNAL TABLE HealthcareAssociatedInfectionsHospital
(
	ProviderID STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	PhoneNumber STRING,
	MeasureName STRING,
	MeasureID STRING,
	ComparedtoNational STRING,
	Score STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HealthcareAssociatedInfectionsHospital";



DROP TABLE HealthcareAssociatedInfectionsNational;
CREATE EXTERNAL TABLE HealthcareAssociatedInfectionsNational
(
	MeasureName STRING,
	MeasureID STRING,
	Score STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HealthcareAssociatedInfectionsNational";



DROP TABLE HealthcareAssociatedInfectionsState;
CREATE EXTERNAL TABLE HealthcareAssociatedInfectionsState
(
	State STRING,
	MeasureName STRING,
	MeasureID STRING,
	Score STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HealthcareAssociatedInfectionsState";



DROP TABLE HospitalGeneralInformation;
CREATE EXTERNAL TABLE HospitalGeneralInformation
(
	ProviderID STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	PhoneNumber STRING,
	HospitalType STRING,
	HospitalOwnership STRING,
	EmergencyServices STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HospitalGeneralInformation";



DROP TABLE HOSPITAL_QUARTERLY_HAC_DOMAIN_HOSPITAL;
CREATE EXTERNAL TABLE HOSPITAL_QUARTERLY_HAC_DOMAIN_HOSPITAL
(
	Hospital_Name STRING,
	ProviderID STRING,
	State STRING,
	FiscalYear STRING,
	Domain_1_Score STRING,
	AHRQ_PSI_90_Score STRING,
	Domain_1_Start_Date STRING,
	Domain_1_End_Date STRING,
	Domain_2_Score STRING,
	CLABSI_Score STRING,
	CAUTI_Score STRING,
	Domain_2_Start_Date STRING,
	Domain_2_End_Date STRING,
	Total_HAC_Score STRING,
	Footnotes STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HOSPITAL_QUARTERLY_HAC_DOMAIN_HOSPITAL";



DROP TABLE HOSPITAL_QUARTERLY_QUALITYMEASURE_IPFQR_HOSPITAL;
CREATE EXTERNAL TABLE HOSPITAL_QUARTERLY_QUALITYMEASURE_IPFQR_HOSPITAL
(
	Provider_Number STRING,
	Hospital_Name STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIP_Code STRING,
	County_Name STRING,
	HBIPS2_Measure_Description STRING,
	HBIPS2_Overall_Rate_Per_1000 STRING,
	HBIPS2_Overall_Num STRING,
	HBIPS2_Overall_Den STRING,
	HBIPS2_Overall_Footnote STRING,
	HBIPS2_112_Rate_Per_1000 STRING,
	HBIPS2_112_Num STRING,
	HBIPS2_112_Den STRING,
	HBIPS2_112_Footnote STRING,
	HBIPS2_1317_Rate_Per_1000 STRING,
	HBIPS2_1317_Num STRING,
	HBIPS2_1317_Den STRING,
	HBIPS2_1317_Footnote STRING,
	HBIPS2_1864_Rate_Per_1000 STRING,
	HBIPS2_1864_Num STRING,
	HBIPS2_1864_Den STRING,
	HBIPS2_1864_Footnote STRING,
	HBIPS2_65_Over_Rate_Per_1000 STRING,
	HBIPS2_65_Over_Num STRING,
	HBIPS2_65_Over_Den STRING,
	HBIPS2_65_Over_Footnote STRING,
	HBIPS3_Measure_Description STRING,
	HBIPS3_Overall_Rate_Per_1000 STRING,
	HBIPS3_Overall_Num STRING,
	HBIPS3_Overall_Den STRING,
	HBIPS3_Overall_Footnote STRING,
	HBIPS3_112_Rate_Per_1000 STRING,
	HBIPS3_112_Num STRING,
	HBIPS3_112_Den STRING,
	HBIPS3_112_Footnote STRING,
	HBIPS3_1317_Rate_Per_1000 STRING,
	HBIPS3_1317_Num STRING,
	HBIPS3_1317_Den STRING,
	HBIPS3_1317_Footnote STRING,
	HBIPS3_1864_Rate_Per_1000 STRING,
	HBIPS3_1864_Num STRING,
	HBIPS3_1864_Den STRING,
	HBIPS3_1864_Footnote STRING,
	HBIPS3_65_Over_Rate_Per_1000 STRING,
	HBIPS3_65_Over_Num STRING,
	HBIPS3_65_Over_Den STRING,
	HBIPS3_65_Over_Footnote STRING,
	HBIPS4_Measure_Description STRING,
	HBIPS4_Overall__of_Total STRING,
	HBIPS4_Overall_Num STRING,
	HBIPS4_Overall_Den STRING,
	HBIPS4_Overall_Footnote STRING,
	HBIPS4_112__of_Total STRING,
	HBIPS4_112_Num STRING,
	HBIPS4_112_Den STRING,
	HBIPS4_112_Footnote STRING,
	HBIPS4_1317__of_Total STRING,
	HBIPS4_1317_Num STRING,
	HBIPS4_1317_Den STRING,
	HBIPS4_1317_Footnote STRING,
	HBIPS4_1864__of_Total STRING,
	HBIPS4_1864_Num STRING,
	HBIPS4_1864_Den STRING,
	HBIPS4_1864_Footnote STRING,
	HBIPS4_65_Over__of_Total STRING,
	HBIPS4_65_Over_Num STRING,
	HBIPS4_65_Over_Den STRING,
	HBIPS4_65_Over_Footnote STRING,
	HBIPS5_Measure_Description STRING,
	HBIPS5_Overall__of_Total STRING,
	HBIPS5_Overall_Num STRING,
	HBIPS5_Overall_Den STRING,
	HBIPS5_Overall_Footnote STRING,
	HBIPS5_112__of_Total STRING,
	HBIPS5_112_Num STRING,
	HBIPS5_112_Den STRING,
	HBIPS5_112_Footnote STRING,
	HBIPS5_1317__of_Total STRING,
	HBIPS5_1317_Num STRING,
	HBIPS5_1317_Den STRING,
	HBIPS5_1317_Footnote STRING,
	HBIPS5_1864__of_Total STRING,
	HBIPS5_1864_Num STRING,
	HBIPS5_1864_Den STRING,
	HBIPS5_1864_Footnote STRING,
	HBIPS5_65_Over__of_Total STRING,
	HBIPS5_65_Over_Num STRING,
	HBIPS5_65_Over_Den STRING,
	HBIPS5_65_Over_Footnote STRING,
	HBIPS6_Measure_Description STRING,
	HBIPS6_Overall__of_Total STRING,
	HBIPS6_Overall_Num STRING,
	HBIPS6_Overall_Den STRING,
	HBIPS6_Overall_Footnote STRING,
	HBIPS6_112__of_Total STRING,
	HBIPS6_112_Num STRING,
	HBIPS6_112_Den STRING,
	HBIPS6_112_Footnote STRING,
	HBIPS6_1317__of_Total STRING,
	HBIPS6_1317_Num STRING,
	HBIPS6_1317_Den STRING,
	HBIPS6_1317_Footnote STRING,
	HBIPS6_1864__of_Total STRING,
	HBIPS6_1864_Num STRING,
	HBIPS6_1864_Den STRING,
	HBIPS6_1864_Footnote STRING,
	HBIPS6_65_Over__of_Total STRING,
	HBIPS6_65_Over_Num STRING,
	HBIPS6_65_Over_Den STRING,
	HBIPS6_65_Over_Footnote STRING,
	HBIPS7_Measure_Description STRING,
	HBIPS7_Overall__of_Total STRING,
	HBIPS7_Overall_Num STRING,
	HBIPS7_Overall_Den STRING,
	HBIPS7_Overall_Footnote STRING,
	HBIPS7_112__of_Total STRING,
	HBIPS7_112_Num STRING,
	HBIPS7_112_Den STRING,
	HBIPS7_112_Footnote STRING,
	HBIPS7_1317__of_Total STRING,
	HBIPS7_1317_Num STRING,
	HBIPS7_1317_Den STRING,
	HBIPS7_1317_Footnote STRING,
	HBIPS7_1864__of_Total STRING,
	HBIPS7_1864_Num STRING,
	HBIPS7_1864_Den STRING,
	HBIPS7_1864_Footnote STRING,
	HBIPS7_65_Over__of_Total STRING,
	HBIPS7_65_Over_Num STRING,
	HBIPS7_65_Over_Den STRING,
	HBIPS7_65_Over_Footnote STRING,
	Start_Date STRING,
	End_Date STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HOSPITAL_QUARTERLY_QUALITYMEASURE_IPFQR_HOSPITAL";



DROP TABLE HOSPITAL_QUARTERLY_QUALITYMEASURE_IPFQR_NATIONAL;
CREATE EXTERNAL TABLE HOSPITAL_QUARTERLY_QUALITYMEASURE_IPFQR_NATIONAL
(
	N_HBIPS2_Measure_Description STRING,
	N_HBIPS2_Overall_Rate_Per_1000 STRING,
	N_HBIPS2_Overall_Num STRING,
	N_HBIPS2_Overall_Den STRING,
	N_HBIPS2_112_Rate_Per_1000 STRING,
	N_HBIPS2_112_Num STRING,
	N_HBIPS2_112_Den STRING,
	N_HBIPS2_1317_Rate_Per_1000 STRING,
	N_HBIPS2_1317_Num STRING,
	N_HBIPS2_1317_Den STRING,
	N_HBIPS2_1864_Rate_Per_1000 STRING,
	N_HBIPS2_1864_Num STRING,
	N_HBIPS2_1864_Den STRING,
	N_HBIPS2_65_Over_Rate_Per_1000 STRING,
	N_HBIPS2_65_Over_Num STRING,
	N_HBIPS2_65_Over_Den STRING,
	N_HBIPS3_Measure_Description STRING,
	N_HBIPS3_Overall_Rate_Per_1000 STRING,
	N_HBIPS3_Overall_Num STRING,
	N_HBIPS3_Overall_Den STRING,
	N_HBIPS3_112_Rate_Per_1000 STRING,
	N_HBIPS3_112_Num STRING,
	N_HBIPS3_112_Den STRING,
	N_HBIPS3_1317_Rate_Per_1000 STRING,
	N_HBIPS3_1317_Num STRING,
	N_HBIPS3_1317_Den STRING,
	N_HBIPS3_1864_Rate_Per_1000 STRING,
	N_HBIPS3_1864_Num STRING,
	N_HBIPS3_1864_Den STRING,
	N_HBIPS3_65_Over_Rate_Per_1000 STRING,
	N_HBIPS3_65_Over_Num STRING,
	N_HBIPS3_65_Over_Den STRING,
	N_HBIPS4_Measure_Description STRING,
	N_HBIPS4_Overall__of_Total STRING,
	N_HBIPS4_Overall_Num STRING,
	N_HBIPS4_Overall_Den STRING,
	N_HBIPS4_112__of_Total STRING,
	N_HBIPS4_112_Num STRING,
	N_HBIPS4_112_Den STRING,
	N_HBIPS4_1317__of_Total STRING,
	N_HBIPS4_1317_Num STRING,
	N_HBIPS4_1317_Den STRING,
	N_HBIPS4_1864__of_Total STRING,
	N_HBIPS4_1864_Num STRING,
	N_HBIPS4_1864_Den STRING,
	N_HBIPS4_65_Over__of_Total STRING,
	N_HBIPS4_65_Over_Num STRING,
	N_HBIPS4_65_Over_Den STRING,
	N_HBIPS5_Measure_Description STRING,
	N_HBIPS5_Overall__of_Total STRING,
	N_HBIPS5_Overall_Num STRING,
	N_HBIPS5_Overall_Den STRING,
	N_HBIPS5_112__of_Total STRING,
	N_HBIPS5_112_Num STRING,
	N_HBIPS5_112_Den STRING,
	N_HBIPS5_1317__of_Total STRING,
	N_HBIPS5_1317_Num STRING,
	N_HBIPS5_1317_Den STRING,
	N_HBIPS5_1864__of_Total STRING,
	N_HBIPS5_1864_Num STRING,
	N_HBIPS5_1864_Den STRING,
	N_HBIPS5_65_Over__of_Total STRING,
	N_HBIPS5_65_Over_Num STRING,
	N_HBIPS5_65_Over_Den STRING,
	N_HBIPS6_Measure_Description STRING,
	N_HBIPS6_Overall__of_Total STRING,
	N_HBIPS6_Overall_Num STRING,
	N_HBIPS6_Overall_Den STRING,
	N_HBIPS6_112__of_Total STRING,
	N_HBIPS6_112_Num STRING,
	N_HBIPS6_112_Den STRING,
	N_HBIPS6_1317__of_Total STRING,
	N_HBIPS6_1317_Num STRING,
	N_HBIPS6_1317_Den STRING,
	N_HBIPS6_1864__of_Total STRING,
	N_HBIPS6_1864_Num STRING,
	N_HBIPS6_1864_Den STRING,
	N_HBIPS6_65_Over__of_Total STRING,
	N_HBIPS6_65_Over_Num STRING,
	N_HBIPS6_65_Over_Den STRING,
	N_HBIPS7_Measure_Description STRING,
	N_HBIPS7_Overall__of_Total STRING,
	N_HBIPS7_Overall_Num STRING,
	N_HBIPS7_Overall_Den STRING,
	N_HBIPS7_112__of_Total STRING,
	N_HBIPS7_112_Num STRING,
	N_HBIPS7_112_Den STRING,
	N_HBIPS7_1317__of_Total STRING,
	N_HBIPS7_1317_Num STRING,
	N_HBIPS7_1317_Den STRING,
	N_HBIPS7_1864__of_Total STRING,
	N_HBIPS7_1864_Num STRING,
	N_HBIPS7_1864_Den STRING,
	N_HBIPS7_65_Over__of_Total STRING,
	N_HBIPS7_65_Over_Num STRING,
	N_HBIPS7_65_Over_Den STRING,
	Start_Date STRING,
	End_Date STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HOSPITAL_QUARTERLY_QUALITYMEASURE_IPFQR_NATIONAL";



DROP TABLE HOSPITAL_QUARTERLY_QUALITYMEASURE_IPFQR_STATE;
CREATE EXTERNAL TABLE HOSPITAL_QUARTERLY_QUALITYMEASURE_IPFQR_STATE
(
	State STRING,
	S_HBIPS2_Measure_Description STRING,
	S_HBIPS2_Overall_Rate_Per_1000 STRING,
	S_HBIPS2_Overall_Num STRING,
	S_HBIPS2_Overall_Den STRING,
	S_HBIPS2_112_Rate_Per_1000 STRING,
	S_HBIPS2_112_Num STRING,
	S_HBIPS2_112_Den STRING,
	S_HBIPS2_1317_Rate_Per_1000 STRING,
	S_HBIPS2_1317_Num STRING,
	S_HBIPS2_1317_Den STRING,
	S_HBIPS2_1864_Rate_Per_1000 STRING,
	S_HBIPS2_1864_Num STRING,
	S_HBIPS2_1864_Den STRING,
	S_HBIPS2_65_Over_Rate_Per_1000 STRING,
	S_HBIPS2_65_Over_Num STRING,
	S_HBIPS2_65_Over_Den STRING,
	S_HBIPS3_Measure_Description STRING,
	S_HBIPS3_Overall_Rate_Per_1000 STRING,
	S_HBIPS3_Overall_Num STRING,
	S_HBIPS3_Overall_Den STRING,
	S_HBIPS3_112_Rate_Per_1000 STRING,
	S_HBIPS3_112_Num STRING,
	S_HBIPS3_112_Den STRING,
	S_HBIPS3_1317_Rate_Per_1000 STRING,
	S_HBIPS3_1317_Num STRING,
	S_HBIPS3_1317_Den STRING,
	S_HBIPS3_1864_Rate_Per_1000 STRING,
	S_HBIPS3_1864_Num STRING,
	S_HBIPS3_1864_Den STRING,
	S_HBIPS3_65_Over_Rate_Per_1000 STRING,
	S_HBIPS3_65_Over_Num STRING,
	S_HBIPS3_65_Over_Den STRING,
	S_HBIPS4_Measure_Description STRING,
	S_HBIPS4_Overall__of_Total STRING,
	S_HBIPS4_Overall_Num STRING,
	S_HBIPS4_Overall_Den STRING,
	S_HBIPS4_112__of_Total STRING,
	S_HBIPS4_112_Num STRING,
	S_HBIPS4_112_Den STRING,
	S_HBIPS4_1317__of_Total STRING,
	S_HBIPS4_1317_Num STRING,
	S_HBIPS4_1317_Den STRING,
	S_HBIPS4_1864__of_Total STRING,
	S_HBIPS4_1864_Num STRING,
	S_HBIPS4_1864_Den STRING,
	S_HBIPS4_65_Over__of_Total STRING,
	S_HBIPS4_65_Over_Num STRING,
	S_HBIPS4_65_Over_Den STRING,
	S_HBIPS5_Measure_Description STRING,
	S_HBIPS5__of_Total STRING,
	S_HBIPS5_Overall_Num STRING,
	S_HBIPS5_Overall_Den STRING,
	S_HBIPS5_112__of_Total STRING,
	S_HBIPS5_112_Num STRING,
	S_HBIPS5_112_Den STRING,
	S_HBIPS5_1317__of_Total STRING,
	S_HBIPS5_1317_Num STRING,
	S_HBIPS5_1317_Den STRING,
	S_HBIPS5_1864__of_Total STRING,
	S_HBIPS5_1864_Num STRING,
	S_HBIPS5_1864_Den STRING,
	S_HBIPS5_65__of_Total STRING,
	S_HBIPS5_65_Over_Num STRING,
	S_HBIPS5_65_Over_Den STRING,
	S_HBIPS6_Measure_Description STRING,
	S_HBIPS6__of_Total STRING,
	S_HBIPS6_Overall_Num STRING,
	S_HBIPS6_Overall_Den STRING,
	S_HBIPS6_112__of_Total STRING,
	S_HBIPS6_112_Num STRING,
	S_HBIPS6_112_Den STRING,
	S_HBIPS6_1317__of_Total STRING,
	S_HBIPS6_1317_Num STRING,
	S_HBIPS6_1317_Den STRING,
	S_HBIPS6_1864__of_Total STRING,
	S_HBIPS6_1864_Num STRING,
	S_HBIPS6_1864_Den STRING,
	S_HBIPS6_65__of_Total STRING,
	S_HBIPS6_65_Over_Num STRING,
	S_HBIPS6_65_Over_Den STRING,
	S_HBIPS7_Measure_Description STRING,
	S_HBIPS7_Overall__of_Total STRING,
	S_HBIPS7_Overall_Num STRING,
	S_HBIPS7_Overall_Den STRING,
	S_HBIPS7_112__of_Total STRING,
	S_HBIPS7_112_Num STRING,
	S_HBIPS7_112_Den STRING,
	S_HBIPS7_1317__of_Total STRING,
	S_HBIPS7_1317_Num STRING,
	S_HBIPS7_1317_Den STRING,
	S_HBIPS7_1864__of_Total STRING,
	S_HBIPS7_1864_Num STRING,
	S_HBIPS7_1864_Den STRING,
	S_HBIPS7_65__of_Total STRING,
	S_HBIPS7_65_Over_Num STRING,
	S_HBIPS7_65_Over_Den STRING,
	Start_Date STRING,
	End_Date STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HOSPITAL_QUARTERLY_QUALITYMEASURE_IPFQR_STATE";



DROP TABLE HOSPITAL_QUARTERLY_QUALITYMEASURE_PCH_HOSPITAL;
CREATE EXTERNAL TABLE HOSPITAL_QUARTERLY_QUALITYMEASURE_PCH_HOSPITAL
(
	PROVIDER_ID STRING,
	Hospital_Name STRING,
	Hospital_Type STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIP_Code STRING,
	County_Name STRING,
	MEASURE_ID STRING,
	MEASURE_DESCRIPTION STRING,
	NUMERATOR STRING,
	DENOMINATOR STRING,
	FOOTNOTE STRING,
	RPTG_PRD_START_DT STRING,
	RPTG_PRD_END_DT STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/HOSPITAL_QUARTERLY_QUALITYMEASURE_PCH_HOSPITAL";



DROP TABLE hvbp_ami_05_28_2015;
CREATE EXTERNAL TABLE hvbp_ami_05_28_2015
(
	ProviderNumber STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	AMI7aPerformanceRate STRING,
	AMI7aAchievementPoints STRING,
	AMI7aImprovementPoints STRING,
	AMI7aMeasureScore STRING,
	AMI8aPerformanceRate STRING,
	AMI8aAchievementPoints STRING,
	AMI8aImprovementPoints STRING,
	AMI8aMeasureScore STRING,
	AMIConditionProcedureScore STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/hvbp_ami_05_28_2015";



DROP TABLE hvbp_Efficiency_05_20_2015;
CREATE EXTERNAL TABLE hvbp_Efficiency_05_20_2015
(
	Provider_Number STRING,
	Hospital_Name STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIP_Code STRING,
	County_Name STRING,
	MSPB1PerformanceRate STRING,
	MSPB1AchievementPoints STRING,
	MSPB1ImprovementPoints STRING,
	MSPB1MeasureScore STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/hvbp_Efficiency_05_20_2015";



DROP TABLE hvbp_hai_05_28_2015;
CREATE EXTERNAL TABLE hvbp_hai_05_28_2015
(
	ProviderNumber STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZipCode STRING,
	CountyName STRING,
	SCIPInf1PerformanceRate STRING,
	SCIPInf1AchievementPoints STRING,
	SCIPInf1ImprovementPoints STRING,
	SCIPInf1MeasureScore STRING,
	SCIPInf2PerformanceRate STRING,
	SCIPInf2AchievementPoints STRING,
	SCIPInf2ImprovementPoints STRING,
	SCIPInf2MeasureScore STRING,
	SCIPInf3PerformanceRate STRING,
	SCIPInf3AchievementPoints STRING,
	SCIPInf3ImprovementPoints STRING,
	SCIPInf3MeasureScore STRING,
	SCIPInf4PerformanceRate STRING,
	SCIPInf4AchievementPoints STRING,
	SCIPInf4ImprovementPoints STRING,
	SCIPInf4MeasureScore STRING,
	SCIPInf9PerformanceRate STRING,
	SCIPInf9AchievementPoints STRING,
	SCIPInf9ImprovementPoints STRING,
	SCIPInf9MeasureScore STRING,
	HAIConditionProcedureScore STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/hvbp_hai_05_28_2015";



DROP TABLE hvbp_hcahps_05_28_2015;
CREATE EXTERNAL TABLE hvbp_hcahps_05_28_2015
(
	ProviderNumber STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	CommunicationwithNursesAchievementPoints STRING,
	CommunicationwithNursesImprovementPoints STRING,
	CommunicationwithNursesDimensionScore STRING,
	CommunicationwithDoctorsAchievementPoints STRING,
	CommunicationwithDoctorsImprovementPoints STRING,
	CommunicationwithDoctorsDimensionScore STRING,
	ResponsivenessofHospitalStaffAchievementPoints STRING,
	ResponsivenessofHospitalStaffImprovementPoints STRING,
	ResponsivenessofHospitalStaffDimensionScore STRING,
	PainManagementAchievementPoints STRING,
	PainManagementImprovementPoints STRING,
	PainManagementDimensionScore STRING,
	CommunicationaboutMedicinesAchievementPoints STRING,
	CommunicationaboutMedicinesImprovementPoints STRING,
	CommunicationaboutMedicinesDimensionScore STRING,
	CleanlinessandQuietnessofHospitalEnvironmentAchievementPoints STRING,
	CleanlinessandQuietnessofHospitalEnvironmentImprovementPoints STRING,
	CleanlinessandQuietnessofHospitalEnvironmentDimensionScore STRING,
	DischargeInformationAchievementPoints STRING,
	DischargeInformationImprovementPoints STRING,
	DischargeInformationDimensionScore STRING,
	OverallRatingofHospitalAchievementPoints STRING,
	OverallRatingofHospitalImprovementPoints STRING,
	OverallRatingofHospitalDimensionScore STRING,
	HCAHPSBaseScore STRING,
	HCAHPSConsistencyScore STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/hvbp_hcahps_05_28_2015";



DROP TABLE hvbp_hf_05_28_2015;
CREATE EXTERNAL TABLE hvbp_hf_05_28_2015
(
	ProviderNumber STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	HF1PerformanceRate STRING,
	HF1AchievementPoints STRING,
	HF1ImprovementPoints STRING,
	HF1MeasureScore STRING,
	HFConditionProcedureScore STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/hvbp_hf_05_28_2015";



DROP TABLE hvbp_outcome_05_18_2015;
CREATE EXTERNAL TABLE hvbp_outcome_05_18_2015
(
	ProviderNumber STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	MORT30AMIPerformanceRate STRING,
	MORT30AMIAchievementPoints STRING,
	MORT30AMIImprovementPoints STRING,
	MORT30AMIMeasureScore STRING,
	MORT30HFPerformanceRate STRING,
	MORT30HFAchievementPoints STRING,
	MORT30HFImprovementPoints STRING,
	MORT30HFMeasureScore STRING,
	MORT30PNPerformanceRate STRING,
	MORT30PNAchievementPoints STRING,
	MORT30PNImprovementPoints STRING,
	MORT30PNMeasureScore STRING,
	PSI90PerformanceRate STRING,
	PSI90AchievementPoints STRING,
	PSI90ImprovementPoints STRING,
	PSI90MeasureScore STRING,
	HAI1_Performance_Rate STRING,
	HAI1AchievementPoints STRING,
	HAI1ImprovementPoints STRING,
	HAI1MeasureScore STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/hvbp_outcome_05_18_2015";



DROP TABLE hvbp_pn_05_28_2015;
CREATE EXTERNAL TABLE hvbp_pn_05_28_2015
(
	ProviderNumber STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	PN3bPerformanceRate STRING,
	PN3bAchievementPoints STRING,
	PN3bImprovementPoints STRING,
	PN3bMeasureScore STRING,
	PN6PerformanceRate STRING,
	PN6AchievementPoints STRING,
	PN6ImprovementPoints STRING,
	PN6MeasureScore STRING,
	PNConditionProcedureScore STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/hvbp_pn_05_28_2015";



DROP TABLE hvbp_quarters;
CREATE EXTERNAL TABLE hvbp_quarters
(
	MeasureID STRING,
	MeasureDescription STRING,
	PerformancePeriod STRING,
	BaselinePeriod STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/hvbp_quarters";



DROP TABLE hvbp_scip_05_28_2015;
CREATE EXTERNAL TABLE hvbp_scip_05_28_2015
(
	ProviderNumber STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	SCIPCard2PerformanceRate STRING,
	SCIPCard2AchievementPoints STRING,
	SCIPCard2ImprovementPoints STRING,
	SCIPCard2MeasureScore STRING,
	SCIPVTE2PerformanceRate STRING,
	SCIPVTE2AchievementPoints STRING,
	SCIPVTE2ImprovementPoints STRING,
	SCIPVTE2MeasureScore STRING,
	SCIPConditionProcedureScore STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/hvbp_scip_05_28_2015";



DROP TABLE hvbp_tps_05_28_2015;
CREATE EXTERNAL TABLE hvbp_tps_05_28_2015
(
	ProviderNumber STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZipCode STRING,
	CountyName STRING,
	UnweightedNormalizedClinicalProcessofCareDomainScore STRING,
	WeightedClinicalProcessofCareDomainScore STRING,
	UnweightedPatientExperienceofCareDomainScore STRING,
	WeightedPatientExperienceofCareDomainScore STRING,
	UnweightedNormalizedOutcomeDomainScore STRING,
	WeightedOutcomeDomainScore STRING,
	UnweightedNormalizedEfficiencyDomainScore STRING,
	WeightedEfficiencyDomainScore STRING,
	TotalPerformanceScore STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/hvbp_tps_05_28_2015";



DROP TABLE MeasureDates;
CREATE EXTERNAL TABLE MeasureDates
(
	MeasureName STRING,
	MeasureID STRING,
	MeasureStartQuarter STRING,
	MeasureStartDate STRING,
	MeasureEndQuarter STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/MeasureDates";



DROP TABLE MedicareHospitalSpendingperPatientHospital;
CREATE EXTERNAL TABLE MedicareHospitalSpendingperPatientHospital
(
	ProviderID STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	PhoneNumber STRING,
	MeasureName STRING,
	MeasureID STRING,
	Score STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/MedicareHospitalSpendingperPatientHospital";



DROP TABLE MedicareHospitalSpendingperPatientNational;
CREATE EXTERNAL TABLE MedicareHospitalSpendingperPatientNational
(
	MeasureName STRING,
	MeasureID STRING,
	Score STRING,
	FootnoteScore STRING,
	NationalMedian STRING,
	FootnoteNationalMedian STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/MedicareHospitalSpendingperPatientNational";



DROP TABLE MedicareHospitalSpendingperPatientState;
CREATE EXTERNAL TABLE MedicareHospitalSpendingperPatientState
(
	State STRING,
	MeasureName STRING,
	MeasureID STRING,
	Score STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/MedicareHospitalSpendingperPatientState";



DROP TABLE OutpatientImagingEfficiencyHospital;
CREATE EXTERNAL TABLE OutpatientImagingEfficiencyHospital
(
	ProviderID STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	PhoneNumber STRING,
	MeasureID STRING,
	MeasureName STRING,
	Score STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/OutpatientImagingEfficiencyHospital";



DROP TABLE OutpatientImagingEfficiencyNational;
CREATE EXTERNAL TABLE OutpatientImagingEfficiencyNational
(
	MeasureID STRING,
	MeasureName STRING,
	Score STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/OutpatientImagingEfficiencyNational";



DROP TABLE OutpatientImagingEfficiencyState;
CREATE EXTERNAL TABLE OutpatientImagingEfficiencyState
(
	State STRING,
	MeasureID STRING,
	MeasureName STRING,
	Score STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/OutpatientImagingEfficiencyState";



DROP TABLE OutpatientProceduresVolume;
CREATE EXTERNAL TABLE OutpatientProceduresVolume
(
	Provider_ID STRING,
	Hospital_Name STRING,
	Measure_ID STRING,
	Gastrointestinal STRING,
	Eye STRING,
	NervousSystem STRING,
	Musculoskeletal STRING,
	Skin STRING,
	Genitourinary STRING,
	Cardiovascular STRING,
	Start_Date STRING,
	End_Date STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/OutpatientProceduresVolume";



DROP TABLE PaymentHospital;
CREATE EXTERNAL TABLE PaymentHospital
(
	ProviderID STRING,
	Hospitalname STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	Countyname STRING,
	Phonenumber STRING,
	Measurename STRING,
	MeasureID STRING,
	Category STRING,
	Denominator STRING,
	Payment STRING,
	Lowerestimate STRING,
	Higherestimate STRING,
	Footnote STRING,
	Measurestartdate STRING,
	Measureenddate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/PaymentHospital";



DROP TABLE PaymentNational;
CREATE EXTERNAL TABLE PaymentNational
(
	MeasureName STRING,
	MeasureID STRING,
	Nationalpayment STRING,
	Numberlessthannationalpayment STRING,
	Numbersameasnationalpayment STRING,
	Numbergreaterthannationalpayment STRING,
	Numberofhospitalstoofew STRING,
	Footnote STRING,
	Measurestartdate STRING,
	Measureenddate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/PaymentNational";



DROP TABLE PaymentState;
CREATE EXTERNAL TABLE PaymentState
(
	State STRING,
	MeasureName STRING,
	MeasureID STRING,
	Numberlessthannationalpayment STRING,
	Numbersameasnationalpayment STRING,
	Numbergreaterthannationalpayment STRING,
	Numberofhospitalstoofew STRING,
	Footnote STRING,
	Measurestartdate STRING,
	Measureenddate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/PaymentState";



DROP TABLE READMISSIONREDUCTION;
CREATE EXTERNAL TABLE READMISSIONREDUCTION
(
	HospitalName STRING,
	ProviderNumber STRING,
	State STRING,
	MeasureName STRING,
	NumberofDischarges STRING,
	Footnote STRING,
	ExcessReadmissionRatio STRING,
	PredictedReadmissionRate STRING,
	ExpectedReadmissionRate STRING,
	NumberofReadmissions STRING,
	StartDate STRING,
	EndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/READMISSIONREDUCTION";



DROP TABLE ReadmissionsandDeathsHospital;
CREATE EXTERNAL TABLE ReadmissionsandDeathsHospital
(
	ProviderID STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	PhoneNumber STRING,
	MeasureName STRING,
	MeasureID STRING,
	ComparedtoNational STRING,
	Denominator STRING,
	Score STRING,
	LowerEstimate STRING,
	HigherEstimate STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/ReadmissionsandDeathsHospital";



DROP TABLE ReadmissionsandDeathsNational;
CREATE EXTERNAL TABLE ReadmissionsandDeathsNational
(
	MeasureName STRING,
	MeasureID STRING,
	NationalRate STRING,
	NumberofHospitalsWorse STRING,
	NumberofHospitalsSame STRING,
	NumberofHospitalsBetter STRING,
	NumberofHospitalsTooFew STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/ReadmissionsandDeathsNational";



DROP TABLE ReadmissionsandDeathsState;
CREATE EXTERNAL TABLE ReadmissionsandDeathsState
(
	State STRING,
	MeasureName STRING,
	MeasureID STRING,
	NumberofHospitalsWorse STRING,
	NumberofHospitalsSame STRING,
	NumberofHospitalsBetter STRING,
	NumberofHospitalsTooFew STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/ReadmissionsandDeathsState";



DROP TABLE StructuralMeasuresHospital;
CREATE EXTERNAL TABLE StructuralMeasuresHospital
(
	ProviderID STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	PhoneNumber STRING,
	MeasureName STRING,
	MeasureID STRING,
	MeasureResponse STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/StructuralMeasuresHospital";



DROP TABLE TimelyandEffectiveCareHospital;
CREATE EXTERNAL TABLE TimelyandEffectiveCareHospital
(
	ProviderID STRING,
	HospitalName STRING,
	Address STRING,
	City STRING,
	State STRING,
	ZIPCode STRING,
	CountyName STRING,
	PhoneNumber STRING,
	Condition STRING,
	MeasureID STRING,
	MeasureName STRING,
	Score STRING,
	Sample STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/TimelyandEffectiveCareHospital";



DROP TABLE TimelyandEffectiveCareNational;
CREATE EXTERNAL TABLE TimelyandEffectiveCareNational
(
	MeasureName STRING,
	MeasureID STRING,
	Condition STRING,
	Category STRING,
	Score STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/TimelyandEffectiveCareNational";



DROP TABLE TimelyandEffectiveCareState;
CREATE EXTERNAL TABLE TimelyandEffectiveCareState
(
	State STRING,
	Condition STRING,
	MeasureName STRING,
	MeasureID STRING,
	Score STRING,
	Footnote STRING,
	MeasureStartDate STRING,
	MeasureEndDate STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",", "quoteChar" = '"', "escapeChar" = '\\')
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/TimelyandEffectiveCareState";



